"""Deterministic planning-artifact validation for dual-agent gates."""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

from .dual_agent import ProbeResult
from .dual_agent_lead import PlanningArtifact, compute_file_sha256


PLANNING_VALIDATOR_VERSION = "1.0.0"

REQUIRED_PLANNING_ARTIFACTS_BY_GATE: dict[str, tuple[str, ...]] = {
    "prd_review": ("prd",),
    "issues_review": ("prd", "issues", "grill_findings"),
    "tdd_review": ("prd", "issues", "tdd_plan", "grill_findings"),
    "implementation_plan": (
        "prd",
        "issues",
        "tdd_plan",
        "grill_findings",
        "implementation_plan",
    ),
    "execution": (
        "prd",
        "issues",
        "tdd_plan",
        "grill_findings",
        "implementation_plan",
    ),
    "outcome_review": (
        "prd",
        "issues",
        "tdd_plan",
        "grill_findings",
        "implementation_plan",
    ),
}

BLOCKED_STUB_PHRASES: tuple[str, ...] = (
    "draft_stub",
    "generated by the supervisor-owned dual-agent workflow driver",
    "no intent supplied",
    "future runs should",
    "placeholder",
    "no tests supplied",
    "no plan supplied",
    "no findings were recorded",
    "someday maybe",
)

STOP_WORDS = {
    "the",
    "and",
    "for",
    "with",
    "that",
    "this",
    "from",
    "into",
    "only",
    "must",
    "will",
    "when",
    "then",
    "they",
    "have",
    "has",
    "are",
    "can",
    "not",
}


@dataclass(frozen=True)
class PlanningCheck:
    check_id: str
    status: str
    message: str = ""
    details: dict[str, Any] = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return self.status == "pass"

    def event_value(self) -> str:
        if self.ok:
            return "pass"
        return f"fail: {self.message}" if self.message else "fail"


@dataclass(frozen=True)
class ArtifactValidation:
    kind: str
    path: str | None
    artifact_hash: str | None
    checks: tuple[PlanningCheck, ...]

    @property
    def ok(self) -> bool:
        return all(check.ok for check in self.checks)


@dataclass(frozen=True)
class PlanningValidationResult:
    gate: str | None
    validator_version: str
    artifacts: tuple[ArtifactValidation, ...]
    checks: dict[str, PlanningCheck]

    @property
    def ok(self) -> bool:
        return all(check.ok for check in self.checks.values())

    @property
    def verdict(self) -> str:
        return "accepted" if self.ok else "blocked"

    @property
    def artifact_hashes(self) -> dict[str, str]:
        hashes: dict[str, str] = {}
        for artifact in self.artifacts:
            if artifact.artifact_hash is not None:
                hashes[artifact.kind] = artifact.artifact_hash
        return hashes

    def to_event_payload(self, *, task_id: str, gate: str | None = None) -> dict[str, Any]:
        return {
            "task_id": task_id,
            "gate": gate or self.gate,
            "validator_version": self.validator_version,
            "artifact_hashes": self.artifact_hashes,
            "checks": {
                check_id: check.event_value()
                for check_id, check in sorted(self.checks.items())
            },
            "verdict": self.verdict,
            "artifacts": [
                {
                    "kind": artifact.kind,
                    "path": artifact.path,
                    "sha256": artifact.artifact_hash,
                    "status": "accepted" if artifact.ok else "blocked",
                }
                for artifact in self.artifacts
            ],
        }


def required_planning_kinds_for_gate(gate: str) -> tuple[str, ...]:
    return REQUIRED_PLANNING_ARTIFACTS_BY_GATE.get(str(gate), ())


def validate_planning_artifacts(
    planning_artifacts: Iterable[PlanningArtifact],
    *,
    required_kinds: Iterable[str] = (),
    gate: str | None = None,
) -> PlanningValidationResult:
    required = tuple(_normalise_kind(kind) for kind in required_kinds)
    by_kind: dict[str, PlanningArtifact] = {}
    for artifact in planning_artifacts:
        kind = _normalise_kind(artifact.kind)
        by_kind.setdefault(kind, artifact)

    texts: dict[str, str] = {}
    artifact_results: list[ArtifactValidation] = []
    checks: dict[str, PlanningCheck] = {}

    missing = [kind for kind in required if kind not in by_kind]
    for kind in required:
        artifact = by_kind.get(kind)
        if artifact is None:
            continue
        path = Path(artifact.path).expanduser()
        if not path.exists() or not path.is_file():
            missing.append(kind)
            artifact_results.append(ArtifactValidation(
                kind=kind,
                path=str(path),
                artifact_hash=None,
                checks=(_fail(f"{_prefix(kind)}-000", f"artifact missing: {path}"),),
            ))
            continue
        text = path.read_text(encoding="utf-8")
        texts[kind] = text
        kind_checks = _validate_kind(kind, text, all_texts=texts)
        artifact_results.append(ArtifactValidation(
            kind=kind,
            path=str(path),
            artifact_hash=compute_file_sha256(path),
            checks=tuple(kind_checks),
        ))
        for check in kind_checks:
            checks[check.check_id] = check

    checks["AGG-001"] = (
        _fail("AGG-001", "missing required planning artifact kinds: " + ", ".join(sorted(set(missing))))
        if missing else _pass("AGG-001", "required planning artifact kinds are present")
    )
    checks["AGG-002"] = _aggregate_distinct_content(texts, required)

    if "implementation_plan" in texts:
        plan_checks = _validate_plan_traceability(texts)
        for check in plan_checks:
            checks[check.check_id] = check

    return PlanningValidationResult(
        gate=gate,
        validator_version=PLANNING_VALIDATOR_VERSION,
        artifacts=tuple(artifact_results),
        checks=checks,
    )


def planning_validation_probe(result: PlanningValidationResult) -> ProbeResult:
    if result.ok:
        return ProbeResult(
            "P_planning",
            "green",
            "planning_validation_ok",
            result.to_event_payload(task_id="", gate=result.gate),
        )
    return ProbeResult(
        "P_planning",
        "red",
        "planning_validation_failed",
        result.to_event_payload(task_id="", gate=result.gate),
    )


def _validate_kind(
    kind: str,
    text: str,
    *,
    all_texts: dict[str, str],
) -> list[PlanningCheck]:
    if kind == "prd":
        return _validate_prd(text)
    if kind == "issues":
        return _validate_issues(text)
    if kind == "tdd_plan":
        return _validate_tdd(text)
    if kind == "grill_findings":
        return _validate_grill(text)
    if kind == "implementation_plan":
        return _validate_plan_shape(text)
    return []


def _validate_prd(text: str) -> list[PlanningCheck]:
    sections = _sections(text)
    required = (
        "problem statement",
        "solution",
        "user stories",
        "prd promise contracts",
        "implementation decisions",
        "testing decisions",
        "out of scope",
    )
    missing_sections = [name for name in required if name not in sections]
    thin_sections = [
        name for name in required
        if name in sections and len(_words(sections[name])) < 12
    ]
    promise_ids = _prd_promise_ids(text)
    promise_block_count = len(promise_ids)
    unique_tokens = _unique_token_count(_strip_headings(text))
    checks = [
        _check("PRD-001", not _has_seed_marker(text), "seed or draft marker present"),
        _check("PRD-002", not _has_stub_phrase(text), "blocked stub phrase present"),
        _check("PRD-003", not missing_sections, "missing sections: " + ", ".join(missing_sections)),
        _check("PRD-004", not thin_sections, "thin section bodies: " + ", ".join(thin_sections)),
        _check("PRD-005", promise_block_count >= 3, f"only {promise_block_count} PRD promise contracts"),
        _check("PRD-006", unique_tokens >= 80, f"only {unique_tokens} unique content tokens"),
    ]
    return checks


def _validate_issues(text: str) -> list[PlanningCheck]:
    slices = _h2_blocks_starting(text, "slice")
    missing_shape: list[str] = []
    missing_priority: list[str] = []
    for index, block in enumerate(slices, start=1):
        lower = block.lower()
        if "scope:" not in lower or "acceptance criteria:" not in lower or "- [ ]" not in lower:
            missing_shape.append(str(index))
        if "priority:" not in lower and "estimate:" not in lower:
            missing_priority.append(str(index))
    return [
        _check("ISS-001", len(slices) >= 2, f"only {len(slices)} implementation slices"),
        _check("ISS-002", not missing_shape, "slices missing scope or acceptance criteria: " + ", ".join(missing_shape)),
        _check("ISS-003", not _has_stub_phrase(text), "blocked future/stub phrase present"),
        _check("ISS-004", not missing_priority, "slices missing priority or estimate: " + ", ".join(missing_priority)),
    ]


def _validate_tdd(text: str) -> list[PlanningCheck]:
    test_names = _tdd_test_names(text)
    vague = [
        name for name in test_names
        if re.fullmatch(r"test_\d+", name) or len(name.replace("_", " ").split()) < 4
    ]
    lower = text.lower()
    maps = re.findall(r"(?im)^\s*maps to\s*:", text)
    return [
        _check("TDD-001", len(test_names) >= 2, f"only {len(test_names)} concrete test names"),
        _check("TDD-002", "red:" in lower and "green:" in lower, "RED/GREEN plan missing"),
        _check("TDD-003", len(maps) >= min(2, len(test_names)), "tests do not map to issues or PRD promises"),
        _check("TDD-004", not vague and len(test_names) >= 2, "vague test names: " + ", ".join(vague)),
    ]


def _validate_grill(text: str) -> list[PlanningCheck]:
    blocks = _h3_blocks_starting(text, "finding")
    statuses: list[str] = []
    invalid_statuses: list[str] = []
    open_findings: list[str] = []
    waived_without_reason: list[str] = []
    for index, block in enumerate(blocks, start=1):
        match = re.search(r"(?im)^\s*status:\s*([a-z_ -]+)\s*$", block)
        if not match:
            invalid_statuses.append(str(index))
            continue
        status = match.group(1).strip().lower()
        statuses.append(status)
        if status not in {"open", "resolved", "waived"}:
            invalid_statuses.append(f"{index}:{status}")
        if status == "open":
            open_findings.append(str(index))
        if status == "waived" and not _has_nonempty_field(block, "reason"):
            waived_without_reason.append(str(index))
    return [
        _check("GRILL-001", bool(statuses) and not invalid_statuses, "invalid or missing finding statuses: " + ", ".join(invalid_statuses)),
        _check("GRILL-002", not open_findings, "open findings: " + ", ".join(open_findings)),
        _check("GRILL-003", not waived_without_reason, "waived findings missing reason: " + ", ".join(waived_without_reason)),
    ]


def _validate_plan_shape(text: str) -> list[PlanningCheck]:
    sections = _sections(text)
    files_body = _first_section(sections, ("files / modules to touch", "files/modules to touch", "modules to touch"))
    risks_body = _first_section(sections, ("risks",))
    trace_body = _first_section(sections, ("traceability",))
    files = re.findall(r"`?[\w.-]+/[\w./-]+\.(?:py|md|toml|yml|yaml)`?", files_body)
    risk_items = re.findall(r"(?m)^\s*[-*]\s+\S+", risks_body)
    return [
        _check("PLAN-001", bool(files), "no files or modules to touch listed"),
        _check("PLAN-002", len(risk_items) >= 2 or len(_words(risks_body)) >= 20, "risks section is too thin"),
        _check("PLAN-003", bool(trace_body.strip()), "traceability block missing"),
    ]


def _validate_plan_traceability(texts: dict[str, str]) -> list[PlanningCheck]:
    plan = texts.get("implementation_plan", "")
    sections = _sections(plan)
    trace_body = _first_section(sections, ("traceability",))
    known_promises = set(_prd_promise_ids(texts.get("prd", "")))
    known_tests = set(_tdd_test_names(texts.get("tdd_plan", "")))
    referenced_promises = set(re.findall(r"\bP\d+\b", trace_body))
    referenced_tests = set(re.findall(r"\btest_[A-Za-z_][A-Za-z0-9_]*\b", trace_body))
    missing_promises = sorted(referenced_promises - known_promises)
    missing_tests = sorted(referenced_tests - known_tests)
    ok = bool(referenced_promises) and bool(referenced_tests) and not missing_promises and not missing_tests
    details = {
        "missing_promises": missing_promises,
        "missing_tests": missing_tests,
    }
    message = []
    if not referenced_promises:
        message.append("no PRD promise references")
    if not referenced_tests:
        message.append("no TDD test references")
    if missing_promises:
        message.append("missing PRD promises: " + ", ".join(missing_promises))
    if missing_tests:
        message.append("missing TDD tests: " + ", ".join(missing_tests))
    return [_check("PLAN-004", ok, "; ".join(message), details=details)]


def _aggregate_distinct_content(texts: dict[str, str], required: tuple[str, ...]) -> PlanningCheck:
    seen: dict[str, str] = {}
    duplicates: list[str] = []
    for kind in required:
        text = texts.get(kind)
        if not text:
            continue
        normalized = _normalise_body(_strip_headings(text))
        if len(normalized) < 80:
            duplicates.append(f"{kind}:nearly_empty")
            continue
        previous = seen.get(normalized)
        if previous is not None:
            duplicates.append(f"{previous}/{kind}")
        seen[normalized] = kind
    return _check("AGG-002", not duplicates, "duplicate or nearly empty artifact bodies: " + ", ".join(duplicates))


def _check(
    check_id: str,
    condition: bool,
    fail_message: str,
    *,
    details: dict[str, Any] | None = None,
) -> PlanningCheck:
    if condition:
        return _pass(check_id)
    return _fail(check_id, fail_message, details=details)


def _pass(check_id: str, message: str = "") -> PlanningCheck:
    return PlanningCheck(check_id=check_id, status="pass", message=message)


def _fail(
    check_id: str,
    message: str,
    *,
    details: dict[str, Any] | None = None,
) -> PlanningCheck:
    return PlanningCheck(
        check_id=check_id,
        status="fail",
        message=message,
        details=details or {},
    )


def _normalise_kind(value: Any) -> str:
    return str(value or "").strip().lower().replace("-", "_")


def _prefix(kind: str) -> str:
    return {
        "prd": "PRD",
        "issues": "ISS",
        "tdd_plan": "TDD",
        "grill_findings": "GRILL",
        "implementation_plan": "PLAN",
    }.get(kind, "ART")


def _sections(text: str) -> dict[str, str]:
    matches = list(re.finditer(r"(?m)^##\s+(.+?)\s*$", text))
    sections: dict[str, str] = {}
    for index, match in enumerate(matches):
        title = _normalise_section_title(match.group(1))
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        sections[title] = text[start:end].strip()
    return sections


def _normalise_section_title(value: str) -> str:
    return re.sub(r"[^a-z0-9/ ]+", "", value.strip().lower()).strip()


def _first_section(sections: dict[str, str], names: tuple[str, ...]) -> str:
    for name in names:
        body = sections.get(_normalise_section_title(name))
        if body is not None:
            return body
    return ""


def _h2_blocks_starting(text: str, prefix: str) -> list[str]:
    return _heading_blocks(text, level=2, prefix=prefix)


def _h3_blocks_starting(text: str, prefix: str) -> list[str]:
    return _heading_blocks(text, level=3, prefix=prefix)


def _heading_blocks(text: str, *, level: int, prefix: str) -> list[str]:
    hashes = "#" * level
    pattern = re.compile(rf"(?m)^{hashes}\s+({re.escape(prefix)}[^\n]*)$", re.IGNORECASE)
    matches = list(pattern.finditer(text))
    blocks: list[str] = []
    for index, match in enumerate(matches):
        start = match.start()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        blocks.append(text[start:end])
    return blocks


def _has_seed_marker(text: str) -> bool:
    lower = text.lower()
    return "draft_stub" in lower or "generated by the supervisor-owned dual-agent workflow driver" in lower


def _has_stub_phrase(text: str) -> bool:
    lower = text.lower()
    if re.search(r"\b(?:tbd|todo)\b", lower):
        return True
    for phrase in BLOCKED_STUB_PHRASES:
        if phrase == "placeholder":
            for line in lower.splitlines():
                stripped = line.strip(" -*\t")
                if "placeholder" in stripped and len(stripped) <= 40:
                    return True
            continue
        if " " in phrase:
            if phrase in lower:
                return True
            continue
        if re.search(rf"\b{re.escape(phrase)}\b", lower):
            return True
    return False


def _strip_headings(text: str) -> str:
    return re.sub(r"(?m)^#{1,6}\s+.*$", "", text)


def _normalise_body(text: str) -> str:
    return re.sub(r"\s+", " ", text.strip().lower())


def _words(text: str) -> list[str]:
    return re.findall(r"[A-Za-z][A-Za-z0-9_/-]{2,}", text)


def _unique_token_count(text: str) -> int:
    return len({
        token.lower()
        for token in _words(text)
        if token.lower() not in STOP_WORDS
    })


def _prd_promise_ids(text: str) -> list[str]:
    return re.findall(r"(?m)^\s*(P\d+)\.\s+\S+", text)


def _tdd_test_names(text: str) -> list[str]:
    names = re.findall(r"(?im)^\s*(?:#{2,4}\s+)?(test_[A-Za-z_][A-Za-z0-9_]*)\b", text)
    names.extend(re.findall(r"(?im)^\s*(?:#{2,4}\s+)?((?:it\s+)?should\s+[^\n]+)$", text))
    return names


def _has_nonempty_field(block: str, field_name: str) -> bool:
    match = re.search(rf"(?im)^\s*{re.escape(field_name)}:\s*(.*)$", block)
    if not match:
        return False
    value = match.group(1).strip()
    if value:
        return True
    rest = block[match.end():]
    for line in rest.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if re.match(r"^[a-z_ -]+:", stripped, re.IGNORECASE):
            return False
        return True
    return False
